name: Continuous deployment

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Run OpenShift build process
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '3.11.230'
      - name: Execute oc commands
        run: |
          oc login --insecure-skip-tls-verify --token ${{ secrets.OPENSHIFT_API_TOKEN }} ${{ secrets.OPENSHIFT_SERVER_URL }}
          oc project hip
          oc start-build quasar-web-app-builder --follow