name: CI

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Run a one-line script
        run: echo Hello, world!

      # Run OpenShift build process
      - name: OpenShift Action
        uses: redhat-developer/openshift-actions@v2.1.0
        with:
          version: '3.11.230'
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT_API_TOKEN }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            oc project ${PROJECT}
            oc start-build quasar-web-app-builder --follow

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
